[BUGFIX] Fix plugin installation by disabling diyChunking
Currently, builds on the Jenkins Chef CI server fail during plugin installations.

Try https://issues.jenkins-ci.org/browse/JENKINS-23223

Error message (appearing at different times):

    Mixlib::ShellOut::ShellCommandFailed

    ------------------------------------

    Expected process to exit with [0], but received '255'

    ---- Begin output of "java" -jar "/opt/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -"remoting" install-plugin file:///opt/kitchen/cache/analysis-collector-1.52.plugin -name analysis-collector  ----

    STDOUT:

    STDERR: Feb 20, 2019 7:26:52 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run

    INFO: I/O error in channel Chunked connection to http://localhost:8080/

    java.io.IOException: Unexpected termination of the channel

    	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)

    Caused by: java.io.EOFException

    	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2638)

    	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3113)

    	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)

    	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)

    	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)

    	at hudson.remoting.Command.readFrom(Command.java:140)

    	at hudson.remoting.Command.readFrom(Command.java:126)

    	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)

    	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)

    hudson.remoting.RemotingSystemException: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@6aa8ceb6:Chunked connection to http://localhost:8080/": channel is already closed

    	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:299)

    	at hudson.remoting.$Proxy1.waitForProperty(Unknown Source)

    	at hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1580)

    	at hudson.cli.CLI.<init>(CLI.java:151)

    	at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:82)

    	at hudson.cli.CLI._main(CLI.java:631)

    	at hudson.cli.CLI.main(CLI.java:427)

    Caused by: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@6aa8ceb6:Chunked connection to http://localhost:8080/": channel is already closed

    	at hudson.remoting.Request.checkIfCanBeExecutedOnChannel(Request.java:129)

    	at hudson.remoting.UserRequest.checkIfCanBeExecutedOnChannel(UserRequest.java:114)

    	at hudson.remoting.Request.call(Request.java:148)

    	at hudson.remoting.Channel.call(Channel.java:954)

    	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)

    	... 6 more

    Caused by: java.io.IOException: Unexpected termination of the channel

    	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)

    Caused by: java.io.EOFException

    	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2638)

    	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3113)

    	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)

    	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)

    	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)

    	at hudson.remoting.Command.readFrom(Command.java:140)

    	at hudson.remoting.Command.readFrom(Command.java:126)

    	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)

    	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)

    ---- End output of "java" -jar "/opt/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -"remoting" install-plugin file:///opt/kitchen/cache/analysis-collector-1.52.plugin -name analysis-collector  ----

    Ran "java" -jar "/opt/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -"remoting" install-plugin file:///opt/kitchen/cache/analysis-collector-1.52.plugin -name analysis-collector  returned 255